<a href="https://colab.research.google.com/github/unpixelate/MLVisual/blob/master/making_computation_easier_w_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.tile(np.array([1,2,3]),(3,5))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [ ]:
#https://stackoverflow.com/questions/53254738/deprecation-status-of-the-numpy-matrix-class
# dont use numpy matrix
# use ndarray instead

In [3]:
# create structured array - named list

x = np.array([('a',0.8),('b',0.4)], dtype=[('label', 'a8'),('prob','f8')])
x['prob']

array([0.8, 0.4])

In [9]:
## rules of broadcast
## if dim of 2 array are equal or one is 1

a = np.arange(1000).reshape((10,1,5,5,4))
b = np.arange(40).reshape((1,10,1,1,4))

# a + b yes can be broadcasted

In [14]:
a = np.arange(25)
print(a.shape)
print(a[:, np.newaxis].shape)
print(a[np.newaxis,:].shape)

(25,)
(25, 1)
(1, 25)


In [17]:
a = np.arange(25).reshape(5,5,1)
a[1,...]

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [18]:
a[1]

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [19]:
a[1,:,:]

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [34]:
a[[1,2,3],[1,2,3]]

array([[ 6],
       [12],
       [18]])

In [23]:
a.squeeze() # remove dim of 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
# ix_ generate a grid --> eg a[np.ix_...] = index all the row (0,0) , (0,2) , (0,3) , (2,0) ...

a[np.ix_([0,2],[0,2,3])]

array([[[ 0],
        [ 2],
        [ 3]],

       [[10],
        [12],
        [13]]])